---
extends: default

yaml-files:
  - '*.kyaml'
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

ignore:
  - "**/flux-system/"

rules:
  indentation:
    spaces: 2

  comments-indentation: false

  truthy:
    check-keys: false

  document-start:
    present: true

  line-length:
    max: 150
