# Path to your oh-my-zsh installation.
export ZSH="/Users/abuelwafa/projects/ohmyzsh"

source ~/projects/dotfiles/.zshrc

alias ql='qlmanage -p'
alias copy='pbcopy'

export ANDROID_HOME=$HOME/Library/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH="/usr/local/sbin:$PATH"
