tap "anchore/syft", trusted: true
tap "anomalyco/tap", trusted: true
tap "dbcli/tap", trusted: true
tap "derailed/k9s", trusted: true
tap "dgunzy/tap", trusted: true
tap "fluxcd/tap", trusted: true
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "kdash-rs/kdash", trusted: true
tap "modem-dev/tap"
tap "nikitabobko/tap"
tap "owenrumney/tools"
tap "shubh-io/tap"
tap "tinted-theming/tinted"

brew "act"
brew "openssl@3"
brew "sqlite"
brew "python@3.14"
brew "tree"
brew "ansible"
brew "bash"
brew "bash-completion@2"
brew "bat"
# brew "btop"
brew "cmake"
brew "cmatrix"
brew "cmus"
brew "cocoapods"
brew "lima"
brew "colima", restart_service: :changed
brew "coreutils"
brew "dive"
brew "docker"
brew "doggo"
brew "dust"
brew "egctl"
brew "fd"
brew "fx"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "goaccess"
brew "graphviz"
brew "grype"
brew "hcloud"
brew "helm"
brew "hey"
brew "htop"
brew "iftop"
brew "ios-deploy"
brew "iredis"
brew "jq"
brew "just"
brew "kanata"
brew "kind"
brew "kompose"
brew "kubectx"
brew "kubernetes-cli"
brew "kustomize"
brew "kyverno"
brew "lazygit"
brew "lazyjournal"
brew "lazysql"
brew "lefthook"
brew "libpq"
brew "qemu"
brew "lima-additional-guestagents"
brew "litecli"
brew "llama.cpp"
brew "lnav"
brew "lua@5.4"
brew "luarocks"
brew "mas"
brew "minikube"
brew "mutt"
brew "mycli"
brew "neovim"
brew "nmap"
brew "node@24"
brew "opentofu"
brew "osv-scanner"
brew "pgcli"
brew "pipx"
brew "pkgconf"
brew "pre-commit"
brew "ripgrep"
brew "shellcheck"
brew "socket_vmnet"
brew "sops"
brew "superfile"
brew "syft"
brew "task"
brew "terragrunt"
brew "tflint"
brew "tmux"
brew "viddy"
brew "vim"
brew "watch"
brew "watchman"
brew "yamllint"
brew "yarn"
brew "yq"
brew "derailed/k9s/k9s"
brew "dgunzy/tap/flux9s"
brew "fluxcd/tap/flux", trusted: true
brew "jesseduffield/lazydocker/lazydocker", trusted: true
brew "kdash-rs/kdash/kdash", trusted: true
brew "modem-dev/tap/hunk", trusted: true
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
go "github.com/asciimoo/wuzz"
go "github.com/google/yamlfmt/cmd/yamlfmt"
cargo "clock-tui"
cargo "tree-sitter-cli"

#------------------------------------------------------
cask "headlamp"
cask "discord", args: { appdir: "/Applications" }
cask "obs", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "firefox", args: { appdir: "/Applications" }

cask "espanso"
cask "font-meslo-lg-nerd-font"
cask "font-jetbrains-mono-nerd-font"
# cask "font-fira-mono-nerd-font"
# cask "font-hack-nerd-font"
# cask "font-inconsolata-go-nerd-font"
# cask "font-roboto-mono-nerd-font"
# cask "font-ubuntu-mono-nerd-font"
# cask "font-ubuntu-sans-nerd-font"

# cask "aerospace"
# cask "lazytrivy"
cask "meld"
cask "stats"

# MAC only apps
cask "coteditor"
mas "Microsoft Excel", id: 462058435
mas "WireGuard", id: 1451685025
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
