# -----------------------------------------
# -----------------------------------------
#
# k config set-context --current --namespace ns_name
# k config
#
# create a debug container within the pod
# k debug my_pod --image alpine -it
#
# k top pod my_pod
#
#
# -----------------------------------------
# -----------------------------------------
---
# network policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ___
  namespace: ___  # namespace for which this network policy is gonna be applied on its pods
spec:
  podSelector:
    matchLabels:
  policyTypes:  # choose policy type to be Ingress only, Egress only or both
    - Ingress
    - Egress
  Ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/32
        - namespaceSelector:
            matchLabels:
            matchExpression:
        - podSelector:
            matchLabels:
            matchExpression:
  Egress:
    - to:
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ___
  labels:
    app.kubernetes.io/name: ___
    app: ___
spec:
  replicas: 2
  revisionHistoryLimit: 10
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ___
      app.kubernetes.io/name: ___
  template:
    metadata:
      labels:
        app: ___
        app.kubernetes.io/name: ___
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: ___
      containers:
        - name: ___
          image: nginx:1.29.7-alpine-slim
          imagePullPolicy: IfNotPresent
          ports:
            - name: app
              containerPort: 3000
              protocol: TCP
          env:
            - name: MY_VAR
              value: my_value
              valueFrom:
                secretKeyRef:
                  name: ___secret_name___
                  key: ___secret_key___
          readinessProbe:
            httpGet:
              path: /api/health
              port: app
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/health
              port: app
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1024Mi
              cpu: 1000m

---
# service
apiVersion: v1

---
# job
apiVersion: batch/v1
kind: Job
metadata:
  name: ___
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ___
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - "echo \"hello kubernets\" && sleep 30"
            # command: ['python3', 'some-script.py']

---
# cronjob
apiVersion: batch/v1
kind: Job
metadata:
  name: ___
spec:
  schedule: "* * * * *"
  jobTemplate:
    # job template without name or api version
    spec:
      template:
        spec:
          containers:
            - name: ___
              restartPolicy: OnFailure
              image: ___
              imagePullPolicy: IfNotPresent
              command:
                - "python3"
                - "some-script.py'"

---
# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: ____
data:
  key: value
  another_key: |
    long form value

---
# secret
apiVersion: v1
kind: Secret
metadata:
data:

---
# daemon-set
apiVersion: v1
kind: DaemonSet
metadata:
spec:
  selector:
    matchLabels:
      name: ___
  template:
    metadata:
      labels:
        name: ___
    spec:
      tolerations:
      containers:

---
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ___
  labels:

---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ___

---
# persistent-volume

---
# persistent-volume-claim

---
# cluster-role

---
# cluster-role-binding

---
# flux kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ___
  namespace: flux-system
spec:
  interval: 60m0s
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  prune: true
  force: false
  targetNamespace: ___
  sourceRef:
    kind: GitRepository
    name: webapp
    namespace: apps
  path: "./deploy/production"

---
# kustomization-patch
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml

---
# helm-repository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ___
  namespace: ___
spec:
  interval: 5m
  url: ___

---
# helm-release
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ___
  namespace: ___
spec:
  releaseName: ___
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ___
      # version: latest
      sourceRef:
        kind: HelmRepository
        name: ___
  values:
