---
k9s:
    liveViewAutoRefresh: true
    screenDumpDir: /Users/abuelwafa/Library/Application Support/k9s/screen-dumps
    refreshRate: 1
    maxConnRetry: 5
    readOnly: false
    noExitOnCtrlC: false
    ui:
        enableMouse: false
        headless: false
        logoless: true
        crumbsless: false
        reactive: false
        noIcons: false
        defaultsToFullScreen: false
    skipLatestRevCheck: false
    disablePodCounting: false
    shellPod:
        image: busybox:1.35.0
        namespace: default
        limits:
            cpu: 100m
            memory: 100Mi
    imageScans:
        enable: false
        exclusions:
            namespaces: []
            labels: {}
    logger:
        tail: 500
        buffer: 5000
        sinceSeconds: -1
        textWrap: true
        showTime: true
    thresholds:
        cpu:
            critical: 90
            warn: 70
        memory:
            critical: 90
            warn: 70
